@startuml
!include colors.pu

class kivy.app.App

class DaumenkivyApp {

}

class kivy.uix.carousel.Carousel

class FlipBook {

}

class kivy.uix.floatlayout.FloatLayout

class Frame {

}

class FileHandler {

}

note "Overview DaumenkivyApp" as N1

kivy.app.App <|-- DaumenkivyApp
kivy.uix.carousel.Carousel <|-- FlipBook
kivy.uix.floatlayout.FloatLayout <|-- Frame

@enduml
